### PR TITLE
Vote parser lib - basic parsing

### PR DESCRIPTION
**Pull request by Totoatmafiascum**

### CODE REVIEW

**Comment by cciccia** [comment]
move stuff in voting to models/voting please.

do you want me to add an endpoint for this?

**Comment by Totoatmafiascum** [comment]
done

Added a couple more files for MathBlade to start working on the advanced VoteNameMatcher.

RE(entry point) I was planning to add /api/v1/topics/{id}/votes as an API entry point (I have it locally but will merge now with your changes, and will push it in a separate CL.

**Comment by Totoatmafiascum** [comment]
Also

**Comment by cciccia** [comment]
I'm gonna close this as I think this should be part of the standalone extension you're building.

**Pull request closed without merging**
